/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ScholenToewijzen;
import java.awt.Cursor;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author Tommy
 */
public class GuiOuderResultNietToegSchoolVol extends javax.swing.JFrame {

    /**
     * Creates new form GuiOuderResultaatZwaarGefaald
     */
    public GuiOuderResultNietToegSchoolVol(BusinessLayer b, Student geselecteerdeStudent) {
        initComponents();
        this.jTextField1.setText("Resultaat toewijzingsaanvraag " + geselecteerdeStudent.getVoornaam() + " " + geselecteerdeStudent.getFamilienaam() + " ("
                +geselecteerdeStudent.getRijksregisternummer() + ")");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton_onderwijsVlaanderen = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton_studyAbroad = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jButton_vclbGent = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jButton_lop = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(122, 200, 248));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 140, 217), 4, true));
        jPanel1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(15, 140, 217));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(15, 140, 217));
        jTextField1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Resultaat toewijzingsaanvraag 'naam kind'");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/V1_8.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(122, 200, 248));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(20, 20, 20));
        jTextArea2.setRows(5);
        jTextArea2.setText("  \n  Beste ouder,\n\n  Alle scholen zijn vol, spijtig genoeg is het ons dus niet gelukt om uw kind toe te \n  wijzen aan een school. Hieronder vindt u enkele alternatieven die u kan overwegen\n  om alsnog een opleiding te vinden voor uw kind.\n\n");
        jTextArea2.setBorder(null);
        jScrollPane2.setViewportView(jTextArea2);

        jButton_onderwijsVlaanderen.setBackground(new java.awt.Color(255, 255, 255));
        jButton_onderwijsVlaanderen.setText("onderwijs vlaanderen");
        jButton_onderwijsVlaanderen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_onderwijsVlaanderenMouseEntered(evt);
            }
        });
        jButton_onderwijsVlaanderen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_onderwijsVlaanderenActionPerformed(evt);
            }
        });

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea3.setSize(490,50);
        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(122, 200, 248));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextArea3.setRows(2);
        jTextArea3.setText("  Hier kan u een database raadplegen van buiten uw regio die nog \n  plaats vrij hebben evenals uitleg m.b.t. thuisonderwijs.");
        jTextArea3.setBorder(null);
        jScrollPane3.setViewportView(jTextArea3);

        jButton_studyAbroad.setBackground(new java.awt.Color(255, 255, 255));
        jButton_studyAbroad.setText("studyabroad");
        jButton_studyAbroad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_studyAbroadMouseEntered(evt);
            }
        });
        jButton_studyAbroad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_studyAbroadActionPerformed(evt);
            }
        });

        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(122, 200, 248));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextArea4.setRows(1);
        jTextArea4.setText("  Hier vindt u info m.b.t. buitenlands onderwijs.");
        jTextArea4.setBorder(null);
        jScrollPane4.setViewportView(jTextArea4);

        jButton_vclbGent.setBackground(new java.awt.Color(255, 255, 255));
        jButton_vclbGent.setText("vrij CLB Aalst");
        jButton_vclbGent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_vclbGentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_vclbGentMouseExited(evt);
            }
        });
        jButton_vclbGent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_vclbGentActionPerformed(evt);
            }
        });

        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(122, 200, 248));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText("  Site van de Centrale Leerlingenbegeleiding van Aalst, u kan hier kan u\n  terecht met al uw vragen of onzekerheden.");
        jScrollPane5.setViewportView(jTextArea5);

        jButton_lop.setBackground(new java.awt.Color(255, 255, 255));
        jButton_lop.setText("LOP");
        jButton_lop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_lopMouseEntered(evt);
            }
        });
        jButton_lop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_lopActionPerformed(evt);
            }
        });

        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea7.setEditable(false);
        jTextArea7.setBackground(new java.awt.Color(122, 200, 248));
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextArea7.setRows(5);
        jTextArea7.setText("  Dit is een organisatie die zich richt op het behouden van gelijke\n  onderwijskansen");
        jScrollPane7.setViewportView(jTextArea7);

        jButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Multiply_20px.png"))); // NOI18N
        jButton1.setText("Sluiten");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_onderwijsVlaanderen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_studyAbroad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_vclbGent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_lop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_onderwijsVlaanderen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_studyAbroad))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_vclbGent))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_lop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton_onderwijsVlaanderenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_onderwijsVlaanderenMouseEntered
        jButton_onderwijsVlaanderen.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_onderwijsVlaanderenMouseEntered

    private void jButton_onderwijsVlaanderenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_onderwijsVlaanderenActionPerformed
        try {

            Desktop.getDesktop().browse(new URI("http://onderwijs.vlaanderen.be/"));

        } catch (IOException | URISyntaxException e1) {
            e1.printStackTrace();  }      // TODO add your handling code here:
    }//GEN-LAST:event_jButton_onderwijsVlaanderenActionPerformed

    private void jButton_studyAbroadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_studyAbroadMouseEntered
        jButton_studyAbroad.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_studyAbroadMouseEntered

    private void jButton_studyAbroadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_studyAbroadActionPerformed
        try {

            Desktop.getDesktop().browse(new URI("https://www.studyabroad.com/"));

        } catch (IOException | URISyntaxException e1) {
            e1.printStackTrace();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton_studyAbroadActionPerformed

    private void jButton_vclbGentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_vclbGentMouseEntered
        jButton_vclbGent.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));   // TODO add your handling code here:
    }//GEN-LAST:event_jButton_vclbGentMouseEntered

    private void jButton_vclbGentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_vclbGentMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_vclbGentMouseExited

    private void jButton_vclbGentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_vclbGentActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://www.vclbaalst.be/"));

        } catch (IOException | URISyntaxException e1) {
            e1.printStackTrace();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton_vclbGentActionPerformed

    private void jButton_lopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_lopMouseEntered
        jButton_lop.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));    // TODO add your handling code here:
    }//GEN-LAST:event_jButton_lopMouseEntered

    private void jButton_lopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_lopActionPerformed
        try {

            Desktop.getDesktop().browse(new URI("http://www.lop.be/"));

        } catch (IOException | URISyntaxException e1) {
            e1.printStackTrace();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton_lopActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiOuderResultNietToegSchoolVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiOuderResultNietToegSchoolVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiOuderResultNietToegSchoolVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiOuderResultNietToegSchoolVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiOuderResultNietToegSchoolVol(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_lop;
    private javax.swing.JButton jButton_onderwijsVlaanderen;
    private javax.swing.JButton jButton_studyAbroad;
    private javax.swing.JButton jButton_vclbGent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
